---- Table: User.User
--
---- DROP TABLE IF EXISTS "User"."User";
--
--CREATE TABLE IF NOT EXISTS "users"."users"
--(
--    "firstName" text COLLATE pg_catalog."default" NOT NULL,
--    "lastName" text COLLATE pg_catalog."default",
--    contact integer,
--    address text COLLATE pg_catalog."default",
--    "UserId" integer NOT NULL,
--    password text COLLATE pg_catalog."default" NOT NULL,
--    email character varying NOT NULL,
--    role text COLLATE pg_catalog."default",
--    CONSTRAINT "User_pkey" PRIMARY KEY ("UserId")
--)
--
--TABLESPACE pg_default;
--
--ALTER TABLE IF EXISTS "users"."users"
--    OWNER to postgres;
